source 'https://github.com/CocoaPods/Specs.git'


target 'M2DPushNotificationManager', :exclusive => true do
  pod "M2DPushNotificationManager", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
